COE-1022: fix echo message

diff --git a/commands/create_user b/commands/create_user
--- a/commands/create_user
+++ b/commands/create_user
@@ -143,7 +143,7 @@ fi
 c8y_User=$(c8y users get --id "$username" 2>&1)
 
 if [ -n "$c8y_User" ] && ! [[ "$c8y_User" == *"Error retrieving user"* ]]; then
-  echo "$username user is already exist on tenant $C8Y_HOST."
+  echo "$username user already exists on tenant $C8Y_HOST."
   exit 0
 fi
 
@@ -176,7 +176,7 @@ fi
 
 output=$(c8y users getUserByName --name "$username" "$@" 2>&1)
 if [[ $output == *"serverError"* ]]; then
-  echo "Error: Created $username user with permission $role failed." >&2
+  echo "Error: Creating $username user with permission $role failed." >&2
   exit 1
 fi
 
